# Generated by Django 3.2 on 2021-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0002_auto_20210417_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='Esite/imge'),
        ),
    ]
