# Generated by Django 3.2 on 2021-04-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0004_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(default='Esite/image/game.jpg', upload_to='Esite/imge'),
        ),
    ]
