# Generated by Django 3.2 on 2021-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0005_alter_mainimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimage',
            name='headding',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mainimage',
            name='subheadding',
            field=models.CharField(default='', max_length=40),
        ),
    ]
