# Generated by Django 3.2 on 2021-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0006_auto_20210420_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=509)),
            ],
        ),
    ]
