# Generated by Django 3.2 on 2021-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0008_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=123456789101),
        ),
    ]
