# Generated by Django 3.2 on 2021-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0012_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_JSON',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=123456789101),
        ),
    ]
