# Generated by Django 3.2 on 2021-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0013_auto_20210524_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateOrder',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('update_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
