# Generated by Django 3.2 on 2021-05-25 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0014_updateorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateorder',
            name='timeStamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
