# Generated by Django 3.2 on 2021-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0015_updateorder_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', upload_to='Esite/imge'),
        ),
    ]
